### ISSUE TITLE
Добавить описание как настроить github tests

### ISSUE THREAD

**Issue by Tritolomei** [AndreyGrandz/Shopify#3]
Скажу честно - я лично не настраивал эти моменты и с ними в деталях не знаком. Но это очень удобные тулы для супер базовых тестов. Нужно добавить описание чтобы младшие разработчики могли с легкостью интегрировать это в свои репозитории.

### Requirements
- Создать файл, условно `github_workflows_ci.yml`, в котором будет готовый сетап с основными тестами.
- Добавить следующие тесты:
  - Проверка коректной сборки sass файлов.
  - Проверка темы используя [`theme check`](https://shopify.dev/themes/tools/theme-check)
  - Проверка на дубликаты (часто при работе с shopify темами мы создаем дубликаты секций/темплейтов. Эта проверка должна просто указывать все ли сходится)
  
  
Вот вам пример из одного из моих проектов. К сожалению настраивал все это не я, так что разобраться нужно будет самостоятельно:
```
name: CI
on: [push]
jobs:
  sass:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-v1-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-v1-

    - run: npm ci
    - run: npm run sass-build

  duplicates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: cmp -s sections/products-discovery.liquid sections/products-discovery-duplicate.liquid
    - run: cmp -s sections/brand-discovery.liquid sections/brand-discovery-duplicate.liquid
    - run: cmp -s sections/worlds.liquid sections/worlds-duplicate.liquid
    - run: cmp -s sections/products-discovery.liquid sections/products-discovery-duplicate-2.liquid
    - run: cmp -s sections/products-discovery.liquid sections/products-discovery-duplicate-3.liquid
    - run: cmp -s sections/products-discovery.liquid sections/products-discovery-duplicate-4.liquid
    - run: cmp -s sections/products-discovery.liquid sections/products-discovery-2.liquid
    - run: cmp -s sections/products-discovery.liquid sections/products-discovery-3.liquid
    - run: cmp -s sections/products-discovery.liquid sections/products-discovery-4.liquid
    - run: cmp -s sections/brand-discovery.liquid sections/brand-discovery-duplicate-2.liquid
    - run: cmp -s sections/brand-discovery.liquid sections/brand-discovery-duplicate-3.liquid
    - run: cmp -s sections/brand-discovery.liquid sections/brand-discovery-duplicate-4.liquid
    - run: cmp -s sections/brand-discovery.liquid sections/brand-discovery-2.liquid
    - run: cmp -s sections/brand-discovery.liquid sections/brand-discovery-3.liquid
    - run: cmp -s sections/brand-discovery.liquid sections/brand-discovery-4.liquid
    - run: cmp -s sections/worlds.liquid sections/worlds-duplicate-2.liquid
    - run: cmp -s sections/worlds.liquid sections/worlds-duplicate-3.liquid
    - run: cmp -s sections/worlds.liquid sections/worlds-duplicate-4.liquid
    - run: cmp -s sections/worlds.liquid sections/worlds-2.liquid
    - run: cmp -s sections/worlds.liquid sections/worlds-3.liquid
    - run: cmp -s sections/worlds.liquid sections/worlds-4.liquid

  theme-check:
    name: theme_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Theme check
        uses: shopify/theme-check-action@v1

```
